version: "3.9"

services:
  # *****************************************************
  # Uncomment this if you need configurate a mock service
  # *****************************************************
  # mock: # please dont change name
  #   image: sheyenrath/wiremock.net
  #   platform: linux/amd64
  #   ports:
  #     - "9091:80" # please dont change ports
  #   networks:
  #     - testvln

  app:
    image: app:test
    depends_on:
      # *****************************************************
      #             addservices dependences here
      # *****************************************************
      # - postgres
    ports:
      # *****************************************************
      #               Configure here ports
      # *****************************************************
      # - "6666:80"
      # - "6667:443"
    platform: linux/amd64
    environment:
      # *****************************************************
      #   Configure here all env vars you need to set
      # *****************************************************
      # Genesis__Host: http://mock
      # Genesis__Port: 80
      # ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    networks:
      - testvln

  itest-init:
    image: itest-init:test
    depends_on:
      - app
      # *****************************************************
      #             addservices dependences here
      # *****************************************************
      # - mock
    platform: linux/amd64
    environment:
      # *****************************************************
      #   Configure here all env vars you need to set
      # *****************************************************
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - testvln

  # *****************************************************
  # Uncomment this if you need configurate a postgres db
  # *****************************************************
  # postgres:
  #   image: postgres
  #   restart: always
  #   platform: linux/amd64
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - testvln
      
networks:
  testvln:
    driver: bridge
