name: platform QA share libraries
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          path: app
      - run: docker build -t share-qa-lib:latest . --platform linux/amd64
        working-directory: app
# need to push image