name: QA platform CI
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      itest_path: 
        required: true
        type: string

jobs:
  build-docker:
    runs-on:
      - self-hosted
      - Linux
      - x64
    steps:
      - name: getting source code
        uses: actions/checkout@v3
        with:
          path: app
      - name: getting itest framework libs
        run: docker run --rm --platform linux/amd64 -v $(pwd):/scripts mauroarias/share-qa-lib:latest /bin/cp -rf /share-qa-libs/ /scripts/
        working-directory: app/${{ inputs.itest_path }}
      - name: Install docker-compose
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          mkdir -p "$HOME/.local/bin"
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o $HOME/.local/bin/docker-compose
          chmod +x $HOME/.local/bin/docker-compose
      - name: build service and run Itest
        run: ${{ inputs.itest_path }}share-qa-libs/scripts/Itest.sh -b "${{ inputs.dockerfile_path }}" -a "linux/amd64"
        working-directory: app
      - name: Publishing Test Report & logs
        uses: actions/upload-artifact@v2
        with:
          name: reporting
          path: app/${{ inputs.itest_path }}reporting