name: QA platform CI
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      itest_path: 
        required: true
        type: string
jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - name: getting source code
        uses: actions/checkout@v3
        with:
          path: app
      - name: getting itest framework libs
        run: docker run --rm -v $(pwd):/scripts mauroarias/share-qa-lib:latest /bin/cp -r /share-qa-libs/ /scripts/
        working-directory: app/${{ inputs.itest_path }}
      - name: building service
        run: docker build -t $(echo ${{ inputs.service_name }} | awk '{print tolower($0)}'):test .
        working-directory: app/${{ inputs.dockerfile_path }}
      - name: run Itest
        run: share-qa-libs/scripts/Itest.sh
        working-directory: app/${{ inputs.itest_path }}
      - name: Publishing Test Report & logs
        uses: actions/upload-artifact@v2
        with:
          name: reporting
          path: app/${{ inputs.itest_path }}/reporting