name: QA platform CI
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_dockerfile_path:
        required: true
        type: string
      service_itest_path: 
        required: true
        type: string
      service_version: 
        type: string
jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - name: getting source code
        uses: actions/checkout@v3
      - name: getting itest framework libs
        run: docker run --rm -v $(pwd):/scripts mauroarias/share-qa-lib:latest /bin/cp -r /share-libs/ /scripts/
      - name: building app
        run: docker build -f "${{inputs.service_dockerfile_path}}" -t "${{inputs.service_name}}":test .
      - name: prepare itest framework libs copy scripts
        run: cp -rf share-libs/scripts/* "${{inputs.service_itest_path}}"/scripts/
      - name: prepare itest framework libs copy dockerfiles
        run: cp -rf share-libs/* "${{inputs.service_itest_path}}"/
      - name: run Itest
        run: "${{inputs.service_itest_path}}"/scripts/Itest.sh
      - name: Publishing Test Report & logs
        uses: actions/upload-artifact@v2
        with:
          name: reporting
          path: reporting